In [2]:
import pandas as pd

df = pd.read_excel("sample_data.xlsx", index_col=0)
df

,east_recto_2_0,east_recto_2_1,east_recto_2_2,north_corrales_1_0,north_corrales_1_1,west_recto_1_0,west_recto_1_1,south_corrales_2_0,south_corrales_2_1
west_recto_0_0,0,0,0,60,60,60,60,60,60
west_recto_0_1,0,0,0,60,60,60,60,60,60
west_recto_0_2,0,0,0,60,60,60,60,60,60
south_corrales_1_0,60,60,60,0,0,0,60,60,60
south_corrales_1_1,60,60,60,0,0,0,60,60,60
east_recto_1_0,60,60,60,0,0,0,60,60,60
east_recto_1_1,60,60,60,0,0,0,60,60,60
north_corrales_0_0,60,60,60,0,0,0,60,60,60
north_corrales_0_1,60,60,60,0,0,0,60,60,60

In [3]:
from_val = []
to_val = []
count = []
for idx_r, row in enumerate(df.index.to_list()):
    for idx_c, column in enumerate(df.columns.to_list()):
        print(row, column)
        from_val.append(df.index.to_list()[idx_r])
        to_val.append(df.columns.to_list()[idx_c])
        count.append(df.iloc[idx_r, idx_c])

new_df = pd.DataFrame({'From': from_val,'To': to_val, 'Count': count})
new_df

west_recto_0_0 east_recto_2_0
west_recto_0_0 east_recto_2_1
west_recto_0_0 east_recto_2_2
west_recto_0_0 north_corrales_1_0
west_recto_0_0 north_corrales_1_1
west_recto_0_0 west_recto_1_0
west_recto_0_0 west_recto_1_1
west_recto_0_0 south_corrales_2_0
west_recto_0_0 south_corrales_2_1
west_recto_0_1 east_recto_2_0
west_recto_0_1 east_recto_2_1
west_recto_0_1 east_recto_2_2
west_recto_0_1 north_corrales_1_0
west_recto_0_1 north_corrales_1_1
west_recto_0_1 west_recto_1_0
west_recto_0_1 west_recto_1_1
west_recto_0_1 south_corrales_2_0
west_recto_0_1 south_corrales_2_1
west_recto_0_2 east_recto_2_0
west_recto_0_2 east_recto_2_1
west_recto_0_2 east_recto_2_2
west_recto_0_2 north_corrales_1_0
west_recto_0_2 north_corrales_1_1
west_recto_0_2 west_recto_1_0
west_recto_0_2 west_recto_1_1
west_recto_0_2 south_corrales_2_0
west_recto_0_2 south_corrales_2_1
south_corrales_1_0 east_recto_2_0
south_corrales_1_0 east_recto_2_1
south_corrales_1_0 east_recto_2_2
south_corrales_1_0 north_corrales_1_0
south_corrales_1_0 north_corrales_1_1
south_corrales_1_0 west_recto_1_0
south_corrales_1_0 west_recto_1_1
south_corrales_1_0 south_corrales_2_0
south_corrales_1_0 south_corrales_2_1
south_corrales_1_1 east_recto_2_0
south_corrales_1_1 east_recto_2_1
south_corrales_1_1 east_recto_2_2
south_corrales_1_1 north_corrales_1_0
south_corrales_1_1 north_corrales_1_1
south_corrales_1_1 west_recto_1_0
south_corrales_1_1 west_recto_1_1
south_corrales_1_1 south_corrales_2_0
south_corrales_1_1 south_corrales_2_1
east_recto_1_0 east_recto_2_0
east_recto_1_0 east_recto_2_1
east_recto_1_0 east_recto_2_2
east_recto_1_0 north_corrales_1_0
east_recto_1_0 north_corrales_1_1
east_recto_1_0 west_recto_1_0
east_recto_1_0 west_recto_1_1
east_recto_1_0 south_corrales_2_0
east_recto_1_0 south_corrales_2_1
east_recto_1_1 east_recto_2_0
east_recto_1_1 east_recto_2_1
east_recto_1_1 east_recto_2_2
east_recto_1_1 north_corrales_1_0
east_recto_1_1 north_corrales_1_1
east_recto_1_1 west_recto_1_0
east_recto_1_1 west_recto_1_1
east_recto_1_1 south_corrales_2_0
east_recto_1_1 south_corrales_2_1
north_corrales_0_0 east_recto_2_0
north_corrales_0_0 east_recto_2_1
north_corrales_0_0 east_recto_2_2
north_corrales_0_0 north_corrales_1_0
north_corrales_0_0 north_corrales_1_1
north_corrales_0_0 west_recto_1_0
north_corrales_0_0 west_recto_1_1
north_corrales_0_0 south_corrales_2_0
north_corrales_0_0 south_corrales_2_1
north_corrales_0_1 east_recto_2_0
north_corrales_0_1 east_recto_2_1
north_corrales_0_1 east_recto_2_2
north_corrales_0_1 north_corrales_1_0
north_corrales_0_1 north_corrales_1_1
north_corrales_0_1 west_recto_1_0
north_corrales_0_1 west_recto_1_1
north_corrales_0_1 south_corrales_2_0
north_corrales_0_1 south_corrales_2_1

                  From                  To  Count
0       west_recto_0_0      east_recto_2_0      0
1       west_recto_0_0      east_recto_2_1      0
2       west_recto_0_0      east_recto_2_2      0
3       west_recto_0_0  north_corrales_1_0     60
4       west_recto_0_0  north_corrales_1_1     60
..                 ...                 ...    ...
76  north_corrales_0_1  north_corrales_1_1      0
77  north_corrales_0_1      west_recto_1_0      0
78  north_corrales_0_1      west_recto_1_1     60
79  north_corrales_0_1  south_corrales_2_0     60
80  north_corrales_0_1  south_corrales_2_1     60

[81 rows x 3 columns]

In [5]:
from_val, to_val, count_val = new_df.iloc[0,:].to_list()

from IPython.display import display

display(from_val, to_val, count_val)

'west_recto_0_0'

'east_recto_2_0'

0

In [6]:
txt = f'<edgeRelation from="{from_val}" to="{to_val}" count="{count_val}"/>'
txt

'<edgeRelation from="west_recto_0_0" to="east_recto_2_0" count="0"/>'

1
1
1
1

IndexError: list index out of range